name: Bug report
description: Report a reproducible issue
labels: [bug]
body:
  - type: textarea
    id: desc
    attributes: { label: Description, description: What happened? }
    validations: { required: true }
  - type: textarea
    id: repro
    attributes: { label: Reproduction, description: Steps + minimal example }
    validations: { required: true }
  - type: input
    id: version
    attributes: { label: ACX version (`acx --version`) }
