name: clamav
on: [push, pull_request]
jobs:
  av-scan:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Install ClamAV
        run: sudo apt-get update && sudo apt-get install -y clamav && sudo freshclam || true
      - name: Scan repo
        run: clamscan -ri . || true
