name: coverage-html
on: [push, pull_request]
jobs:
  coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: Install gcovr
        run: sudo apt-get update && sudo apt-get install -y gcovr
      - name: Build with coverage
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DACX_WITH_COVERAGE=ON -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
          cmake --build build
      - name: Run tests
        run: ctest --test-dir build --output-on-failure || true
      - name: Generate HTML report
        run: mkdir -p coverage && gcovr -r . --html --html-details -o coverage/index.html
      - name: Upload coverage site
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage
