name: docs
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: false
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - name: Install MkDocs Material
        run: pip install mkdocs-material
      - name: Build site
        run: mkdocs build -d site
      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site
