name: labeler
on:
  pull_request_target:
    types: [opened, synchronize]
jobs:
  triage:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: false
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: false
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v5
        with: { configuration-path: .github/labeler.yml }
