name: workflow-policy
on: [push, pull_request]
jobs:
  conftest:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: false
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - uses: instrumenta/conftest-action@master
        with:
          files: .github/workflows
          policy: policies/workflows
