name: Scorecard
on:
  branch_protection_rule:
  schedule:
    - cron: '0 9 * * 1'
  push:
    branches: [ main, master ]
permissions: read-all
jobs:
  analysis:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ossf/scorecard-action@v2.3.1
        with:
          results_file: scorecard.json
          results_format: json
      - uses: actions/upload-artifact@v4
        with:
          name: scorecard
          path: scorecard.json
