name: scorecards
on:
  schedule:
    - cron: '24 3 * * 1'
  push:
    branches: [ main, master ]
  pull_request:
permissions:
  security-events: write
  id-token: write
  contents: read
jobs:
  analysis:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false }}
    timeout-minutes: 30
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: ossf/scorecard-action@v2.3.3
        with:
          results_format: sarif
          results_file: results.sarif
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
